/*
 * Decompiled with CFR 0.152.
 */
package rpg;

import rpg.f;

public interface d {
    public static final byte[] a_ = "yes".getBytes();
    public static final byte[] b_ = "Would you like to revive?".getBytes();
    public static final byte[] g_f0_AB;
    public static final byte[] h_f0_AB;
    public static final byte[] i_f0_AB;
    public static final byte[] j;
    public static final byte[] k;
    public static final byte[] l;
    public static final byte[] m;
    public static final byte[] n;
    public static final byte[] o;
    public static final byte[] p;
    public static final byte[] q;
    public static final byte[][] b;
    public static final byte[][] c;
    public static final byte[][] d;
    public static final byte[][] e;
    public static final byte[] r;
    public static final byte[][] f;
    public static final byte[][] g_f1_AAB;
    public static final byte[] s;
    public static final byte[] t;
    public static final byte[] u;
    public static final byte[] v;
    public static final byte[] w;
    public static final byte[] x;
    public static final byte[] y;
    public static final byte[] z;
    public static final byte[] A;
    public static final byte[][] h_f1_AAB;
    public static final byte[] B;
    public static final byte[] C;
    public static final byte[] D;
    public static final byte[] E;
    public static final byte[] F;
    public static final byte[] G;
    public static final byte[] H;
    public static final byte[] I;
    public static final byte[] J;
    public static final byte[] K;
    public static final byte[] L;
    public static final byte[] M;
    public static final byte[] N;
    public static final byte[] O;
    public static final byte[] P;
    public static final int e_;
    public static final int f_;
    public static final int i_f1_I;

    static {
        "Portrait used count =".getBytes();
        "learning".getBytes();
        g_f0_AB = "Refining Stones ".getBytes();
        h_f0_AB = "red stone".getBytes();
        i_f0_AB = "polishing powder".getBytes();
        j = "Amethyst".getBytes();
        " more".getBytes();
        "Room".getBytes();
        "blank".getBytes();
        "Character Conversion: Menu Keys [".getBytes();
        "ended up]".getBytes();
        "youngso]".getBytes();
        "number]".getBytes();
        "symbol]".getBytes();
        "Hangul]".getBytes();
        "a".getBytes();
        k = "more".getBytes();
        "Former costs".getBytes();
        "G is.".getBytes();
        l = "yes".getBytes();
        m = "No".getBytes();
        "Want to play more? You need to".getBytes();
        "TRY AND BUY?".getBytes();
        n = "LV".getBytes();
        o = "#".getBytes();
        p = "NULL".getBytes();
        q = "Failed! Please try again".getBytes();
        "Congratulations! You have activated this game!".getBytes();
        b = new byte[][]{"You have already purchased ".getBytes(), ". ;You do not need to buy it again.".getBytes()};
        byte[][] byArrayArray = new byte[][]{"Purchase ".getBytes(), " for ".getBytes(), " RMB.".getBytes(), " ".getBytes(), " ;You have finished ".getBytes(), ", still need to send ".getBytes(), ", continue?".getBytes()};
        c = new byte[][]{"Purchase ".getBytes(), " for ".getBytes(), " RMB.;Do you want to purchase now?".getBytes()};
        d = new byte[][]{"You have purchased ".getBytes(), " successfully! ".getBytes()};
        e = new byte[][]{"20000 gold".getBytes(), "Double EXP".getBytes(), "Double Money".getBytes(), "Pocket Shop".getBytes(), "Increase level".getBytes(), "Magic combine".getBytes(), "Resurrect".getBytes()};
        r = "Bought".getBytes();
        f = new byte[][]{"Purchase 20000 gold".getBytes(), "Purchase double exp".getBytes(), "Purchase double coin earning".getBytes(), "Purchase pocket shop".getBytes(), "Purchase 10 levels increase".getBytes(), "Purchase instant magic combo.".getBytes(), "Resurrect and invincible for 5 sec.".getBytes()};
        g_f1_AAB = new byte[][]{"Price: ".getBytes(), "RMB".getBytes()};
        "LV".getBytes();
        "EXP".getBytes();
        "HP".getBytes();
        "SP".getBytes();
        "ATK".getBytes();
        "DEF".getBytes();
        "CRITICAL".getBytes();
        "DODGE".getBytes();
        "DEXINTCONSTR".getBytes();
        s = "Gold".getBytes();
        t = "Public storage can store and transfer your gold, equipments, and items. You can select a slot, and then transfer the gold, equipments, and items stored in public storage. You can use 1,3 keys to switch between personal and public storage.".getBytes();
        u = "Are you sure you want to quit?".getBytes();
        v = "Your current class does not allow you to equip with this equipment.".getBytes();
        w = "This combination does not require any elements.".getBytes();
        x = "Please select the combination book.".getBytes();
        y = "Please start or load a game before purchasing this item.".getBytes();
        z = "You do not have all the elements required for this combination.;You can force combine magic for 1RMB.;Do you want to purchase the combination now?".getBytes();
        A = "You has reached the highest level, can no longer raise".getBytes();
        h_f1_AAB = new byte[][]{"Level up! You have reached level ".getBytes(), ".;".getBytes()};
        B = "You do not have enough gold.;".getBytes();
        "You do not have all the elements required for this combination.;You can force combine magic.;".getBytes();
        C = "Press Any Key To Continue".getBytes();
        D = "Please play game in portrait mode.".getBytes();
        E = new byte[]{-14, 119, -14, 120, -15, 48, -14, 71, -16, -50, -15, 88, 46, 46, 46};
        F = "Do you want to continue? ;Your game will exit.".getBytes();
        G = "Go to www.eamobile.com to get ;more EA games for your phone!".getBytes();
        H = " The fee for changing professions is ".getBytes();
        I = " Gold. Continue?".getBytes();
        J = new byte[]{0, 0, 0, -1, 1, -1, 1, -1, 1, 0, 0, -2, 2, 0, 0, -3, 3, -1, 1, 1, -1, -2, -2, 2, 2};
        K = new byte[]{0, -1, 1, 0, 0, -1, -1, 1, 1, -2, 2, 0, 0, -3, 3, 0, 0, -2, -2, 2, 2, -1, 1, -1, 1};
        L = new byte[]{0, 6, 7, 5, 8};
        M = new byte[]{0, 5, 8, 7, 6};
        N = new byte[]{0, 4, 3, 1, 2};
        O = new byte[]{0, 3, 4, 2, 1};
        P = new byte[]{0, 2, 1, 4, 3};
        e_ = rpg.f.b;
        f_ = rpg.f.a;
        i_f1_I = f_ - 16;
    }
}

